// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2o-K0hlV72Jn7FRTV2H5xWBIBzUwR8ug',
    appId: '1:883755220754:android:4d727dd11b694d363b7dcb',
    messagingSenderId: '883755220754',
    projectId: 'to-the-blessing',
    storageBucket: 'to-the-blessing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0szNZSBni7FvALcu4DHVa1Zcu_RO_uA',
    appId: '1:883755220754:ios:557dff0b2ff581213b7dcb',
    messagingSenderId: '883755220754',
    projectId: 'to-the-blessing',
    storageBucket: 'to-the-blessing.firebasestorage.app',
    androidClientId: '883755220754-ejlhvq11gmr8rkdb1002trkp5dda0ipl.apps.googleusercontent.com',
    iosClientId: '883755220754-hv7vtdmeco37o9ae2tisif0kdp3uo3e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.totheblessing',
  );

}